//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTn.Json.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZTn.Json.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion action failed.
        /// </summary>
        internal static string DeletionActionFailed {
            get {
                return ResourceManager.GetString("DeletionActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Array.
        /// </summary>
        internal static string InsertArray {
            get {
                return ResourceManager.GetString("InsertArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Object.
        /// </summary>
        internal static string InsertObject {
            get {
                return ResourceManager.GetString("InsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Property as Array.
        /// </summary>
        internal static string InsertPropertyAsArray {
            get {
                return ResourceManager.GetString("InsertPropertyAsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Property as Object.
        /// </summary>
        internal static string InsertPropertyAsObject {
            get {
                return ResourceManager.GetString("InsertPropertyAsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Property as Value.
        /// </summary>
        internal static string InsertPropertyAsValue {
            get {
                return ResourceManager.GetString("InsertPropertyAsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Value.
        /// </summary>
        internal static string InsertValue {
            get {
                return ResourceManager.GetString("InsertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json Array.
        /// </summary>
        internal static string JsonArray {
            get {
                return ResourceManager.GetString("JsonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json Object.
        /// </summary>
        internal static string JsonObject {
            get {
                return ResourceManager.GetString("JsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Json Object.
        /// </summary>
        internal static string NewJsonObject {
            get {
                return ResourceManager.GetString("NewJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste action failed.
        /// </summary>
        internal static string PasteActionFailed {
            get {
                return ResourceManager.GetString("PasteActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Node After.
        /// </summary>
        internal static string PasteNodeAfter {
            get {
                return ResourceManager.GetString("PasteNodeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Node Before.
        /// </summary>
        internal static string PasteNodeBefore {
            get {
                return ResourceManager.GetString("PasteNodeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
    }
}
